deel_task:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "sb10459.eu-west-3.aws"  
      user: DEELTESTACCOUNT
      password: "{{ env_var('DBT_PASSWORD_DEEL') }}"
      role: ACCOUNTADMIN
      database: DEEL_HOME_TEST
      warehouse: COMPUTE_WH
      schema: RAW
      threads: 1
